name: CI

on:
  push:
    branches: ["dev1", "development"]

jobs: 
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install Poetry
        run: pip install poetry 
      - name: Install dependencies
        working-directory: simple_notes_app
        run: poetry install
      - name: Run tests
        working-directory: simple_notes_app
        run: poetry run pytest tests/
